operator = "router"
state = "stateless"
port = "50450"

maxWorkers = 4
maxJobQueue = 10000

[Evaluation]
tracing = false
logTimestamps = false

[[connections]]
address = "sum-stories:50350"
local = "local"
[[connections]]
address = "sum-comments:50360"
local = "local"
