qpuType = "sum"
port = "50251"

maxWorkers = 4
maxJobQueue = 10000

[Evaluation]
tracing = false
logTimestamps = false

[[connections]]
# address = "dsdriver:50150"
address = "127.0.0.1:50150"
local = "local"

[StateBackend]
endpoint = "127.0.0.1:3308"

[StateBackend.Credentials]
accessKeyID = "root"
secretAccessKey = "123456"

[SumConfig]
SourceTable = "votes"
RecordIDAttribute = ["story_id", "comment_id"]
AttributeToSum = "vote"
[SumConfig.Query]
Projection = ["id", "story_id", "comment_id", "vote"]
IsNotNull = ["comment_id"]