operator = "db_driver"
state = "stateless"
port = "50150"

maxWorkers = 4
maxJobQueue = 10000

[[InputSchema]]
table = "buck"
[[InputSchema.Attributes]]
key = "x-amz-meta-f-tripdistance"
type = "float"

[Evaluation]
tracing = false
logTimestamps = false

[DatastoreConfig]
type = "s3"
endpoint = "http://127.0.0.1:8001"
logStreamEndpoint = "127.0.0.1:50001"
DBName = "proteus_lobsters_db"
[DatastoreConfig.Credentials]
accessKeyID = "accessKey1"
secretAccessKey = "verySecretKey1"