#  docker run --rm -ti --name sum -p 127.0.0.1:50250:50250 -v (pwd)/configs:/configs -e MYSQL_PASSWORD="verySecrectQPUPwd" qpu/dev /configs/lobsters/localdev/sum-stories.toml trace

qpuType = "sum"
port = "50250"

maxWorkers = 4
maxJobQueue = 10000

[Evaluation]
tracing = false
logTimestamps = false

[[connections]]
address = "127.0.0.1:50150"
local = "local"

[StateBackend]
endpoint = "127.0.0.1:3308"

[StateBackend.Credentials]
accessKeyID = "root"
secretAccessKey = "verySecrectQPUPwd"

[SumConfig]
SourceTable = "votes"
RecordIDAttribute = ["story_id"]
AttributeToSum = "vote"
[SumConfig.Query]
Projection = ["id", "story_id", "vote"]
IsNull = ["comment_id"]
