version: '3'
services:
  datastore-proteus:
    image: datastore/proteus:latest
    networks:
      - proteus_net
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - ${PWD}/build/datastore/lobsters-MySQL/docker-entrypoint-init.d/setup-proteus.sh:/docker-entrypoint-initdb.d/setup.sh
      - ${PWD}/build/datastore/lobsters-MySQL/docker-entrypoint-init.d/maxconn.cnf:/etc/mysql/conf.d/maxconn.cnf
    ports:
      - 3307:3306
      - 50000:50000
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.datastore == true ]

networks:
  proteus_net:
    external: true