qpuType = "dbdriver"
port = "50150"

[dataStoreConfig]
type = "s3"
endpoint = "http://cloudserver-0:8000"
logStreamEndpoint = "cloudserver-0:50000"
awsAccessKeyID = "accessKey1"
awsSecretAccessKey = "verySecretKey1"

[dataStoreConfig.dataset]
  db = "1"
  dc = "1"
  shard = "1"