qpuType = "dbdriver"
port = "50150"

[dataStoreConfig]
type = "s3"
endpoint = "127.0.0.1:8001"
logStreamEndpoint = "localhost:50001"
awsAccessKeyID = "accessKey1"
awsSecretAccessKey = "verySecretKey1"

[dataStoreConfig.dataset]
  db = "1"
  dc = "1"
  shard = "1"