qpuType = "datastore_driver"
port = "50150"

[dataStoreConfig]
type = "mysql"
# endpoint = "http://cloudserver-0:8000"
# logStreamEndpoint = "cloudserver-0:50000"
endpoint = "http://127.0.0.1:8001"
logStreamEndpoint = "127.0.0.1:50000"

[[Schema]]
table = "votes"
  [[Schema.Attributes]]
  key = "story_id"
  type = "int"
  [[Schema.Attributes]]
  key = "comment_id"
  type = "int"
  [[Schema.Attributes]]
  key = "vote"
  type = "int"


[dataStoreConfig.dataset]
  db = "1"
  dc = "1"
  shard = "1"