qpuType = "join"
port = "50350"

[[connections]]
address = "127.0.0.1:50150"
local = "local"
[[connections]]
address = "127.0.0.1:50250"
local = "local"

[StateBackend]
endpoint = "127.0.0.1:3308"

[StateBackend.Credentials]
accessKeyID = "root"
secretAccessKey = "123456"

[[Schema]]
table = "stories"
[[Schema.Attributes]]
key = "id"
type = "int"
[[Schema.Attributes]]
key = "user_id"
type = "int"
[[Schema.Attributes]]
key = "title"
type = "string"
[[Schema.Attributes]]
key = "description"
type = "string"
[[Schema.Attributes]]
key = "short_id"
type = "string"

[[Schema]]
table = "stories_with_votes"
[[Schema.Attributes]]
key = "story_id"
type = "int"
[[Schema.Attributes]]
key = "vote_count"
type = "int"
