[Connection]
"endpoint" = "127.0.0.1:3309"
"database" = "proteus_lobsters_db"
"accessKeyID" = "user"
"secretAccessKey"  = "verySecretPwd"

[Benchmark]
"opCount" = 5
"runtime" = 5
"doWarmup" = false
"warmup" = 2
"threadCount" = 1

[Operations]
"writeRatio" = 0.1
"downVoteRatio" = 0.2

[Operations.Homepage]
"storiesLimit" = 5

[Preload.RecordCount]
"users" = 5
"stories" = 5
"comments" = 5