[Connection]
"endpoint" = "127.0.0.1:3307"
"database" = "proteus_lobsters_db"
"accessKeyID" = "root"
"secretAccessKey"  = "verySecretPwd"

[Benchmark]
"opCount" = 100000
"runtime" = 30
"doWarmup" = true
"warmup" = 15
"threadCount" = 1

[Operations]
"writeRatio" = 0.0
"downVoteRatio" = 0.2

[Operations.Homepage]
"storiesLimit" = 5

[Preload.RecordCount]
"users" = 10
"stories" = 100
"comments" = 10
"StoryVotes" = 10