tracing = true

[Connection]
endpoint = "127.0.0.1:3307"
database = "proteus_lobsters_db"
accessKeyID = "root"
secretAccessKey  = "verySecretPwd"

[Benchmark]
opCount = 1000000
runtime = 300
doWarmup = true
warmup = 60
threadCount = 1

[Operations]
writeRatio = 0.1
downVoteRatio = 0.2

[Operations.Homepage]
storiesLimit = 5

[Preload.RecordCount]
users = 10
stories = 1000
comments = 100
StoryVotes = 10000
