version: '3'
services:
  datastore-mv:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - /mount/schema-mv.sql:/docker-entrypoint-initdb.d/schema-mv.sql
      # - ${PWD}/build/datastore/lobsters-MySQL/docker-entrypoint-init/schema-mv.sql:/docker-entrypoint-initdb.d/schema-mv.sql
    ports:
      - 3307:3306
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.datastore == true ]