version: '3'
services:
  datastore-plain:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - /mount/setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - /mount/maxconn.cnf:/etc/mysql/conf.d/maxconn.cnf
    ports:
      - 3307:3306
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.datastore == true ]