version: '3'
services:
  datastore:
    image: dvasilas/proteus-lobsters:5ab5c800
    networks:
      - proteus_net
    environment:
    - MYSQL_ROOT_PASSWORD=verySecretPwd
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.datastore == true ]

networks:
  proteus_net:
    external: true