version: '3'
services:
  datastore-plain:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      # - /mount/schema-plain.sql:/docker-entrypoint-initdb.d/schema-plain.sql
      - ${PWD}/build/datastore/lobsters-MySQL/docker-entrypoint-init/schema-plain.sql:/docker-entrypoint-initdb.d/schema-plain.sql
    ports:
      - 3307:3306
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.datastore == true ]