version: '3'
services:
  datastore-plain:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - /mount/setup-plain.sh:/docker-entrypoint-initdb.d/setup.sh
      - /mount/proteus-lobsters/small-plain.sql:/opt/proteus-lobsters/small-plain.sql
      - /mount/maxconn.cnf:/etc/mysql/conf.d/maxconn.cnf
    ports:
      - 3307:3306
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc==eu
          - node.labels.placement_datastore==true