version: '3'
services:
  datastore-proteus:
    image: dvasilas/proteus-lobsters:${TAG_DATASTORE}
    networks:
      - proteus_net
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - ${HOME}/volume/setup-proteus.sh:/docker-entrypoint-initdb.d/setup.sh
      - ${HOME}/volume/proteus-lobsters/small.sql:/opt/proteus-lobsters/small.sql
      - ${HOME}/volume/proteus-lobsters/med.sql:/opt/proteus-lobsters/med.sql
      - ${HOME}/volume/maxconn.cnf:/etc/mysql/conf.d/maxconn.cnf
    ports:
      - 3307:3306
      - 50000:50000
    cap_add:
      - SYS_NICE
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == 2
          - node.labels.placement_datastore == true

networks:
  proteus_net:
    external: true
