version: '3'
services:
  dsdriver:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - proteus_net
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
      - ${HOME}/volume/scripts:/opt/proteus-lobsters/freshness
    ports:
      - 50150:50150
    command: /configs/lobsters/dsdriver.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == 2
          - node.labels.placement_dsdriver == true

  sum-stories:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
      - ${HOME}/volume/scripts:/opt/proteus-lobsters/freshness
    ports:
      - 50250:50250
    command: /configs/lobsters/sum-stories.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == 2
          - node.labels.placement_sum == true

  join-stories:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
      - ${HOME}/volume/scripts:/opt/proteus-lobsters/freshness
    ports:
      - 50350:50350
    command: /configs/lobsters/join-stories.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == 2
          - node.labels.placement_join == true

networks:
  qpu_graph:
  proteus_net:
    external: true
