version: '3'
services:
  dsdriver:
    image: qpu/dev
    # networks:
      # - proteus_net
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - /Users/dimvas/go/src/github.com/dvasilas/proteus/configs:/configs
    command: /configs/lobsters/dsdriver.toml trace
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.queryengine == true ]
  sum:
    image: qpu/dev
    # networks:
      # - proteus_net
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - /Users/dimvas/go/src/github.com/dvasilas/proteus/configs:/configs
    command: /configs/lobsters/sum-stories.toml trace
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.queryengine == true ]
  join:
    image: qpu/dev
    # networks:
      # - proteus_net
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - /Users/dimvas/go/src/github.com/dvasilas/proteus/configs:/configs
    ports:
      - 50350:50350
    command: /configs/lobsters/join.toml trace
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.queryengine == true ]

# networks:
#   proteus_net:
#     external: true