version: '3'
services:
  dsdriver:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - proteus_net
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - /mount/configs:/configs
    command: /configs/lobsters/dsdriver.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_dsdriver == true

  sum:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - /mount/configs:/configs
    command: /configs/lobsters/sum-stories.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_sum == true

  join:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - /mount/configs:/configs
    ports:
      - 50350:50350
    command: /configs/lobsters/join-stories.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_join == true

networks:
  qpu_graph:
  proteus_net:
    external: true
